name: CI Laravel Pint

on:
  pull_request:
    branches:
      - main
jobs:
  lint-commit-msg:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: npm install
      - name: Lint commit message
        run: npx commitlint --last --verbose
  pint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --no-scripts

      - name: Run Laravel Pint
        run: vendor/bin/pint --test
